version: "2.1"
networks:
  barwa:
    driver: bridge
services:
  devbox:
    build: ./deploybox
    volumes:
      - ./webmob_gbm_barwa-oci_app:/opt/barwa:rw
      - /dev/bus/usb/:/dev/bus/usb/:ro
      - ./deploybox/settings.xml:/usr/share/maven/conf/settings.xml:rw
    privileged: true
    devices: 
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - 10081:10081
      - 3001:3001
    networks:
      - barwa
  mobilefirst:
    build: ./mobile-first
    command: /root/MobileFirst-8.0.0.0/run.sh
    volumes:
      - ./server.xml:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/server.xml:rw
      - ./bootstrap.properties:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/bootstrap.properties:rw
      - ./jvm.options:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/jvm.options:rw
      - ./logs/:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/logs/:rw
      - ./resources/:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/resources/:rw
      - ./wars/:/home/wars:rw
      - ./webmob_gbm_barwa-oci_app:/opt/barwa:rw
    ports:
      - 9080:9080
    networks:
      - barwa
  sonarqube:
    #build: ./sonar
    image: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
      - 9200:9001
    volumes:
      #- ./webmob_gbm_barwa-oci_app:/opt/barwa:rw
      - ./sonar/plugins:/opt/sonarqube/extensions/plugins/:rw
    networks:
      - barwa
  ship:
    image: portainer/portainer
    mem_limit: 100m
    networks:
      - barwa
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock