version: "2.1"
networks:
  mfp:
    driver: bridge
services:
  mfp:
    build: .
    mem_limit: 1500m
    command: /root/MobileFirst-8.0.0.0/run.sh
    volumes:
      - ./server.xml:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/server.xml:rw
      - ./bootstrap.properties:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/bootstrap.properties:rw
      - ./jvm.options:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/jvm.options:rw
      - ./logs/:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/logs/:rw
      - ./resources/:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/resources/:rw
     #- ./apps:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/apps:rw
      - ./wars/:/opt/wars:rw
      - ./analytics/:/root/MobileFirst-8.0.0.0/mfp-server/usr/servers/mfp/analyticsData/:rw
    ports:
      - 9080:9080
    networks:
      - mfp
  analytics:
    image: elasticsearch:1.5
    mem_limit: 512m
    depends_on:
      - mfp
    volumes:
      - ./analytics/worklight:/usr/share/elasticsearch/data/:rw
    ports:
      - 9200:9200
      - 9300:9300
  ship:
    image: portainer/portainer
    mem_limit: 50m
    networks:
      - mfp
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock